name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
  build-nginx-image:
    name: Build Nginx Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push latest images
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thinksvip/lnmp:nginx

      - name: Login to Aliyun Container Registry
        run: |
          docker version
          docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
          docker build ./nginx --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:nginx
          docker push registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:nginx

  build-php-image:
    name: Build PHP Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push latest images
        uses: docker/build-push-action@v4
        with:
          context: ./php/php
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thinksvip/lnmp:php-alpine

      - name: Login to Aliyun Container Registry
        run: |
          docker version
          docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
          docker build ./php/php --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:php-alpine
          docker push registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:php-alpine

  build-php8-image:
    name: Build PHP8 Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push latest images
        uses: docker/build-push-action@v4
        with:
          context: ./php/php8
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thinksvip/lnmp:php8-alpine

      - name: Login to Aliyun Container Registry
        run: | 
          docker version
          docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
          docker build ./php/php8 --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:php8-alpine
          docker push registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:php8-alpine
          
  build-queue-image:
    name: Build Queue Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push latest images
        uses: docker/build-push-action@v4
        with:
          context: ./php/php-queue
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thinksvip/lnmp:queue
      - name: Login to Aliyun Container Registry
        run: | 
          docker version
          docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
          docker build ./php/php-queue --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:queue
          docker push registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:queue
          
  build-mysql-image:
    name: Build MySQL Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push latest images
        uses: docker/build-push-action@v4
        with:
          context: ./mysql
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thinksvip/lnmp:mysql

      - name: Login to Aliyun Container Registry
        run: | 
          docker version
          docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
          docker build ./mysql --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:mysql
          docker push registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:mysql

  build-redis-image:
    name: Build Redis Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push latest images
        uses: docker/build-push-action@v4
        with:
          context: ./redis
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thinksvip/lnmp:redis

      - name: Login to Aliyun Container Registry
        run: | 
          docker version
          docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
          docker build ./redis --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:redis
          docker push registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:redis
           
  build-node-image:
    name: Build Node Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push latest images
        uses: docker/build-push-action@v4
        with:
          context: ./node
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thinksvip/lnmp:node
 
      - name: Login to Aliyun Container Registry
        run: | 
          docker version
          docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
          docker build ./node --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:node
          docker push registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:node 

  build-php-xdebug-image:
    name: Build PHP Xdebug Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push latest images
        uses: docker/build-push-action@v4
        with:
          context: ./php/php-xdebug
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thinksvip/lnmp:php-alpine-dev

      - name: Login to Aliyun Container Registry
        run: | 
          docker version
          docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
          docker build ./php/php-xdebug --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:php-alpine-dev
          docker push registry.cn-shenzhen.aliyuncs.com/thinks/lnmp:php-alpine-dev           